validator_set_address: "0x9687e8c41fa369ad08fd278a43114c4207856a61"
profile_address: "0x3b67c8D22a91572a6AB18acC9F70787Af04A4043"
staking_address: "0x9C245671791834daf3885533D24dce516B763B28"
trusted_org_address: "0x7507dc433a98E1fE105d69f19f3B40E4315A4F32"
slash_indicator_address: "0xF7837778b6E180Df6696C8Fa986d62f8b6186752"
validator_set_storage_slot:
  candidateIds_slot: 115
  candidate_index_slot: 116
  candidate_info_slot: 117
  validator_map_slot: 172
  validatorIds_slot: 171
  validator_count_slot: 170
  validator_candidate_offset: 
    admin_offset: 0
    consensus_addr_offset: 1
    treasury_addr_offset: 2
    commission_rate_offset: 4
profile_storage_slot:
  id2profile_slot: 0
  registry_slot: 1
  consensus2Id_slot: 2
  candidate_profile_offset:
    id_offset: 0
    consensus_offset: 1
    admin_offset: 2
    treasury_offset: 3
    governor_offset: 4
    pubkey_offset: 5
staking_storage_slot:
  pool_detail_slot: 55
  staking_pool_slot: 3
  user_reward_slot: 2
  admin_of_active_pool_mapping_slot: 58
  pool_detail_offset:
    pid_offset: 0
    shadowed_pool_admin_offset: 1
    staking_amount_offset: 2
    staking_total_offset: 3
    delegating_amount_offset: 4
    last_delegating_timestamp_offset: 5
  pool_fields_offset:
    shares_inner_offset: 1
    shares_last_period_offset: 2
  user_reward_fields_offset:
    lowest_amount_offset: 2
    last_period_offset: 3
trusted_org_slot:
  consensus_list_slot: 9
  governor_list_slot: 10
  added_block_slot: 8
  total_weight_slot: 3
  consensus_weight_slot: 5
  governor_weight_slot: 6
slash_indicator_slot:
  credit_score_slot: 220

new_validator_configs:
  - candidate_admin: "0xE5635B0172e7488072348a0395C983DfDA68755A"
    consensus_addr: "0x13377331DEAD"
    treasury_addr: "0xE5635B0172e7488072348a0395C983DfDA68755A"
    commission_rate: "1000"
    pubkey: "a49891083c05e85a9023d20097367d5c203bfaa4b0f02753dbb85580508fbacee0fb7e7235c7fc032176d97e3e3b101c"
    governor_addr:
     
new_blank_wallets:
  - wallet_addr: "0x4a6c63a216711A4ec59938b784223967A2206aeE" 
  - wallet_addr: "0xd3f52d3837Db34c644372ADaE7b0f8c0Cf44BB4D"
  - wallet_addr: "0xFE490b68E64B190B415Bb92F8D2F7566243E6ea0" 
  - wallet_addr: "0x29973913ab9D66fd7744e126f2E5029294de1317"
  - wallet_addr: "0xF43e76f1E97e81571fe8165676F774D757Da9aE8"
  - wallet_addr: "0x8d57D53fE556376075DafA13d30aA1B98D731945"
  - wallet_addr: "0xAdc7f35a772F2fEc70b9f0bD79fABD5F4Ed02f06"
  - wallet_addr: "0xc56e395AFfE1aBa503F57986EDd27ebAd164f4D8"
  - wallet_addr: "0x5C3d79b9e8f9Df760473CcAe6FA9230EFE646680"
  - wallet_addr: "0x4c664200fefb2C21F119D4400a807E6aaFF94ee3"

blank_wallet_balance: 1000
# number of period of hardfork - 3 
last_period: 812
# at block timestamp, at which before hardfork - 3 days
last_delegating_timestamp: 999999999
chain_id: 2021
